name: Maven Publish

on:
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update Maven settings.xml with token
        run: |
          mkdir -p ~/.m2
          cp ${{ github.workspace }}/settings.xml ~/.m2/settings.xml
          sed -i 's|<password>.*</password>|<password>${{ secrets.GITHUB_TOKEN }}</password>|g' ~/.m2/settings.xml


      - name: Publish to GitHub Packages
        run: mvn -B deploy -s ~/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
