name: Publish/deploy maven

on:
  release:
    type: [created]
  pull_request:
    branches: ["main"]

jobs:
build:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
        server-id: github
        settings-path: ${{ github.workflow }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish package maven
      run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
